apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
  labels:
    app: logger-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - name: logger-service
          image: muzaffertolgayakar/logger-service:2.0.0
          ports:
            - containerPort: 80